name: cg-bpf

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          # pip install . && pip install -r requirements_dev.txt && pip install pytest
          which python
          which python3
      
      # - uses: JavidDitty/setup-cgbpf@main
          
      - name: Test with pytest
        run: |
          # python3 run_all_tests.py

      - name: Upload CG-BPF Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CGBPF_ARTIFACT_NAME }}
          path: ${{ env.CGBPF_LOGS }}
